// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgreq.proto

package com.fly.netty.codec.protobuf;

public final class MsgReqProtobuf {
  private MsgReqProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code NetType}
   */
  public enum NetType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>wifi = 0;</code>
     */
    wifi(0),
    /**
     * <code>mobile = 1;</code>
     */
    mobile(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>wifi = 0;</code>
     */
    public static final int wifi_VALUE = 0;
    /**
     * <code>mobile = 1;</code>
     */
    public static final int mobile_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static NetType valueOf(int value) {
      return forNumber(value);
    }

    public static NetType forNumber(int value) {
      switch (value) {
        case 0: return wifi;
        case 1: return mobile;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<NetType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        NetType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<NetType>() {
            public NetType findValueByNumber(int number) {
              return NetType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.fly.netty.codec.protobuf.MsgReqProtobuf.getDescriptor().getEnumTypes().get(0);
    }

    private static final NetType[] VALUES = values();

    public static NetType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private NetType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:NetType)
  }

  public interface CabinOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Cabin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *充电舱编号
     * </pre>
     *
     * <code>string c_id = 1;</code>
     */
    java.lang.String getCId();
    /**
     * <pre>
     *充电舱编号
     * </pre>
     *
     * <code>string c_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getCIdBytes();

    /**
     * <pre>
     *充电宝RFID
     * </pre>
     *
     * <code>string p_id = 2;</code>
     */
    java.lang.String getPId();
    /**
     * <pre>
     *充电宝RFID
     * </pre>
     *
     * <code>string p_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getPIdBytes();

    /**
     * <pre>
     *充电宝锁状态
     * </pre>
     *
     * <code>bool p_lock = 3;</code>
     */
    boolean getPLock();

    /**
     * <pre>
     *充电宝循环次数
     * </pre>
     *
     * <code>int32 p_count = 4;</code>
     */
    int getPCount();

    /**
     * <pre>
     *电量
     * </pre>
     *
     * <code>int32 p_quantity = 5;</code>
     */
    int getPQuantity();
  }
  /**
   * Protobuf type {@code Cabin}
   */
  public  static final class Cabin extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Cabin)
      CabinOrBuilder {
    // Use Cabin.newBuilder() to construct.
    private Cabin(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Cabin() {
      cId_ = "";
      pId_ = "";
      pLock_ = false;
      pCount_ = 0;
      pQuantity_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Cabin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              cId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              pId_ = s;
              break;
            }
            case 24: {

              pLock_ = input.readBool();
              break;
            }
            case 32: {

              pCount_ = input.readInt32();
              break;
            }
            case 40: {

              pQuantity_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fly.netty.codec.protobuf.MsgReqProtobuf.internal_static_Cabin_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fly.netty.codec.protobuf.MsgReqProtobuf.internal_static_Cabin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin.class, com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin.Builder.class);
    }

    public static final int C_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object cId_;
    /**
     * <pre>
     *充电舱编号
     * </pre>
     *
     * <code>string c_id = 1;</code>
     */
    public java.lang.String getCId() {
      java.lang.Object ref = cId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *充电舱编号
     * </pre>
     *
     * <code>string c_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCIdBytes() {
      java.lang.Object ref = cId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int P_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object pId_;
    /**
     * <pre>
     *充电宝RFID
     * </pre>
     *
     * <code>string p_id = 2;</code>
     */
    public java.lang.String getPId() {
      java.lang.Object ref = pId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *充电宝RFID
     * </pre>
     *
     * <code>string p_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPIdBytes() {
      java.lang.Object ref = pId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int P_LOCK_FIELD_NUMBER = 3;
    private boolean pLock_;
    /**
     * <pre>
     *充电宝锁状态
     * </pre>
     *
     * <code>bool p_lock = 3;</code>
     */
    public boolean getPLock() {
      return pLock_;
    }

    public static final int P_COUNT_FIELD_NUMBER = 4;
    private int pCount_;
    /**
     * <pre>
     *充电宝循环次数
     * </pre>
     *
     * <code>int32 p_count = 4;</code>
     */
    public int getPCount() {
      return pCount_;
    }

    public static final int P_QUANTITY_FIELD_NUMBER = 5;
    private int pQuantity_;
    /**
     * <pre>
     *电量
     * </pre>
     *
     * <code>int32 p_quantity = 5;</code>
     */
    public int getPQuantity() {
      return pQuantity_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cId_);
      }
      if (!getPIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, pId_);
      }
      if (pLock_ != false) {
        output.writeBool(3, pLock_);
      }
      if (pCount_ != 0) {
        output.writeInt32(4, pCount_);
      }
      if (pQuantity_ != 0) {
        output.writeInt32(5, pQuantity_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cId_);
      }
      if (!getPIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, pId_);
      }
      if (pLock_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, pLock_);
      }
      if (pCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, pCount_);
      }
      if (pQuantity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, pQuantity_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin)) {
        return super.equals(obj);
      }
      com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin other = (com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin) obj;

      boolean result = true;
      result = result && getCId()
          .equals(other.getCId());
      result = result && getPId()
          .equals(other.getPId());
      result = result && (getPLock()
          == other.getPLock());
      result = result && (getPCount()
          == other.getPCount());
      result = result && (getPQuantity()
          == other.getPQuantity());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + C_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCId().hashCode();
      hash = (37 * hash) + P_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPId().hashCode();
      hash = (37 * hash) + P_LOCK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getPLock());
      hash = (37 * hash) + P_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getPCount();
      hash = (37 * hash) + P_QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getPQuantity();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Cabin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Cabin)
        com.fly.netty.codec.protobuf.MsgReqProtobuf.CabinOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fly.netty.codec.protobuf.MsgReqProtobuf.internal_static_Cabin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fly.netty.codec.protobuf.MsgReqProtobuf.internal_static_Cabin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin.class, com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin.Builder.class);
      }

      // Construct using com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        cId_ = "";

        pId_ = "";

        pLock_ = false;

        pCount_ = 0;

        pQuantity_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fly.netty.codec.protobuf.MsgReqProtobuf.internal_static_Cabin_descriptor;
      }

      public com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin getDefaultInstanceForType() {
        return com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin.getDefaultInstance();
      }

      public com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin build() {
        com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin buildPartial() {
        com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin result = new com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin(this);
        result.cId_ = cId_;
        result.pId_ = pId_;
        result.pLock_ = pLock_;
        result.pCount_ = pCount_;
        result.pQuantity_ = pQuantity_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin) {
          return mergeFrom((com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin other) {
        if (other == com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin.getDefaultInstance()) return this;
        if (!other.getCId().isEmpty()) {
          cId_ = other.cId_;
          onChanged();
        }
        if (!other.getPId().isEmpty()) {
          pId_ = other.pId_;
          onChanged();
        }
        if (other.getPLock() != false) {
          setPLock(other.getPLock());
        }
        if (other.getPCount() != 0) {
          setPCount(other.getPCount());
        }
        if (other.getPQuantity() != 0) {
          setPQuantity(other.getPQuantity());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object cId_ = "";
      /**
       * <pre>
       *充电舱编号
       * </pre>
       *
       * <code>string c_id = 1;</code>
       */
      public java.lang.String getCId() {
        java.lang.Object ref = cId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *充电舱编号
       * </pre>
       *
       * <code>string c_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCIdBytes() {
        java.lang.Object ref = cId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *充电舱编号
       * </pre>
       *
       * <code>string c_id = 1;</code>
       */
      public Builder setCId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *充电舱编号
       * </pre>
       *
       * <code>string c_id = 1;</code>
       */
      public Builder clearCId() {
        
        cId_ = getDefaultInstance().getCId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *充电舱编号
       * </pre>
       *
       * <code>string c_id = 1;</code>
       */
      public Builder setCIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pId_ = "";
      /**
       * <pre>
       *充电宝RFID
       * </pre>
       *
       * <code>string p_id = 2;</code>
       */
      public java.lang.String getPId() {
        java.lang.Object ref = pId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *充电宝RFID
       * </pre>
       *
       * <code>string p_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPIdBytes() {
        java.lang.Object ref = pId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *充电宝RFID
       * </pre>
       *
       * <code>string p_id = 2;</code>
       */
      public Builder setPId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *充电宝RFID
       * </pre>
       *
       * <code>string p_id = 2;</code>
       */
      public Builder clearPId() {
        
        pId_ = getDefaultInstance().getPId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *充电宝RFID
       * </pre>
       *
       * <code>string p_id = 2;</code>
       */
      public Builder setPIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pId_ = value;
        onChanged();
        return this;
      }

      private boolean pLock_ ;
      /**
       * <pre>
       *充电宝锁状态
       * </pre>
       *
       * <code>bool p_lock = 3;</code>
       */
      public boolean getPLock() {
        return pLock_;
      }
      /**
       * <pre>
       *充电宝锁状态
       * </pre>
       *
       * <code>bool p_lock = 3;</code>
       */
      public Builder setPLock(boolean value) {
        
        pLock_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *充电宝锁状态
       * </pre>
       *
       * <code>bool p_lock = 3;</code>
       */
      public Builder clearPLock() {
        
        pLock_ = false;
        onChanged();
        return this;
      }

      private int pCount_ ;
      /**
       * <pre>
       *充电宝循环次数
       * </pre>
       *
       * <code>int32 p_count = 4;</code>
       */
      public int getPCount() {
        return pCount_;
      }
      /**
       * <pre>
       *充电宝循环次数
       * </pre>
       *
       * <code>int32 p_count = 4;</code>
       */
      public Builder setPCount(int value) {
        
        pCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *充电宝循环次数
       * </pre>
       *
       * <code>int32 p_count = 4;</code>
       */
      public Builder clearPCount() {
        
        pCount_ = 0;
        onChanged();
        return this;
      }

      private int pQuantity_ ;
      /**
       * <pre>
       *电量
       * </pre>
       *
       * <code>int32 p_quantity = 5;</code>
       */
      public int getPQuantity() {
        return pQuantity_;
      }
      /**
       * <pre>
       *电量
       * </pre>
       *
       * <code>int32 p_quantity = 5;</code>
       */
      public Builder setPQuantity(int value) {
        
        pQuantity_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *电量
       * </pre>
       *
       * <code>int32 p_quantity = 5;</code>
       */
      public Builder clearPQuantity() {
        
        pQuantity_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Cabin)
    }

    // @@protoc_insertion_point(class_scope:Cabin)
    private static final com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin();
    }

    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Cabin>
        PARSER = new com.google.protobuf.AbstractParser<Cabin>() {
      public Cabin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Cabin(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Cabin> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Cabin> getParserForType() {
      return PARSER;
    }

    public com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MachineOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Machine)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *机器码
     * </pre>
     *
     * <code>string m_id = 1;</code>
     */
    java.lang.String getMId();
    /**
     * <pre>
     *机器码
     * </pre>
     *
     * <code>string m_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getMIdBytes();

    /**
     * <pre>
     *网络模式
     * </pre>
     *
     * <code>.NetType netType = 2;</code>
     */
    int getNetTypeValue();
    /**
     * <pre>
     *网络模式
     * </pre>
     *
     * <code>.NetType netType = 2;</code>
     */
    com.fly.netty.codec.protobuf.MsgReqProtobuf.NetType getNetType();

    /**
     * <pre>
     *充电舱
     * </pre>
     *
     * <code>.Cabin cabin = 3;</code>
     */
    boolean hasCabin();
    /**
     * <pre>
     *充电舱
     * </pre>
     *
     * <code>.Cabin cabin = 3;</code>
     */
    com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin getCabin();
    /**
     * <pre>
     *充电舱
     * </pre>
     *
     * <code>.Cabin cabin = 3;</code>
     */
    com.fly.netty.codec.protobuf.MsgReqProtobuf.CabinOrBuilder getCabinOrBuilder();
  }
  /**
   * Protobuf type {@code Machine}
   */
  public  static final class Machine extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Machine)
      MachineOrBuilder {
    // Use Machine.newBuilder() to construct.
    private Machine(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Machine() {
      mId_ = "";
      netType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Machine(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              mId_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              netType_ = rawValue;
              break;
            }
            case 26: {
              com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin.Builder subBuilder = null;
              if (cabin_ != null) {
                subBuilder = cabin_.toBuilder();
              }
              cabin_ = input.readMessage(com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(cabin_);
                cabin_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fly.netty.codec.protobuf.MsgReqProtobuf.internal_static_Machine_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fly.netty.codec.protobuf.MsgReqProtobuf.internal_static_Machine_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine.class, com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine.Builder.class);
    }

    public static final int M_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object mId_;
    /**
     * <pre>
     *机器码
     * </pre>
     *
     * <code>string m_id = 1;</code>
     */
    public java.lang.String getMId() {
      java.lang.Object ref = mId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *机器码
     * </pre>
     *
     * <code>string m_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMIdBytes() {
      java.lang.Object ref = mId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NETTYPE_FIELD_NUMBER = 2;
    private int netType_;
    /**
     * <pre>
     *网络模式
     * </pre>
     *
     * <code>.NetType netType = 2;</code>
     */
    public int getNetTypeValue() {
      return netType_;
    }
    /**
     * <pre>
     *网络模式
     * </pre>
     *
     * <code>.NetType netType = 2;</code>
     */
    public com.fly.netty.codec.protobuf.MsgReqProtobuf.NetType getNetType() {
      com.fly.netty.codec.protobuf.MsgReqProtobuf.NetType result = com.fly.netty.codec.protobuf.MsgReqProtobuf.NetType.valueOf(netType_);
      return result == null ? com.fly.netty.codec.protobuf.MsgReqProtobuf.NetType.UNRECOGNIZED : result;
    }

    public static final int CABIN_FIELD_NUMBER = 3;
    private com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin cabin_;
    /**
     * <pre>
     *充电舱
     * </pre>
     *
     * <code>.Cabin cabin = 3;</code>
     */
    public boolean hasCabin() {
      return cabin_ != null;
    }
    /**
     * <pre>
     *充电舱
     * </pre>
     *
     * <code>.Cabin cabin = 3;</code>
     */
    public com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin getCabin() {
      return cabin_ == null ? com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin.getDefaultInstance() : cabin_;
    }
    /**
     * <pre>
     *充电舱
     * </pre>
     *
     * <code>.Cabin cabin = 3;</code>
     */
    public com.fly.netty.codec.protobuf.MsgReqProtobuf.CabinOrBuilder getCabinOrBuilder() {
      return getCabin();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mId_);
      }
      if (netType_ != com.fly.netty.codec.protobuf.MsgReqProtobuf.NetType.wifi.getNumber()) {
        output.writeEnum(2, netType_);
      }
      if (cabin_ != null) {
        output.writeMessage(3, getCabin());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mId_);
      }
      if (netType_ != com.fly.netty.codec.protobuf.MsgReqProtobuf.NetType.wifi.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, netType_);
      }
      if (cabin_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getCabin());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine)) {
        return super.equals(obj);
      }
      com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine other = (com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine) obj;

      boolean result = true;
      result = result && getMId()
          .equals(other.getMId());
      result = result && netType_ == other.netType_;
      result = result && (hasCabin() == other.hasCabin());
      if (hasCabin()) {
        result = result && getCabin()
            .equals(other.getCabin());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + M_ID_FIELD_NUMBER;
      hash = (53 * hash) + getMId().hashCode();
      hash = (37 * hash) + NETTYPE_FIELD_NUMBER;
      hash = (53 * hash) + netType_;
      if (hasCabin()) {
        hash = (37 * hash) + CABIN_FIELD_NUMBER;
        hash = (53 * hash) + getCabin().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Machine}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Machine)
        com.fly.netty.codec.protobuf.MsgReqProtobuf.MachineOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fly.netty.codec.protobuf.MsgReqProtobuf.internal_static_Machine_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fly.netty.codec.protobuf.MsgReqProtobuf.internal_static_Machine_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine.class, com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine.Builder.class);
      }

      // Construct using com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        mId_ = "";

        netType_ = 0;

        if (cabinBuilder_ == null) {
          cabin_ = null;
        } else {
          cabin_ = null;
          cabinBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fly.netty.codec.protobuf.MsgReqProtobuf.internal_static_Machine_descriptor;
      }

      public com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine getDefaultInstanceForType() {
        return com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine.getDefaultInstance();
      }

      public com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine build() {
        com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine buildPartial() {
        com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine result = new com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine(this);
        result.mId_ = mId_;
        result.netType_ = netType_;
        if (cabinBuilder_ == null) {
          result.cabin_ = cabin_;
        } else {
          result.cabin_ = cabinBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine) {
          return mergeFrom((com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine other) {
        if (other == com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine.getDefaultInstance()) return this;
        if (!other.getMId().isEmpty()) {
          mId_ = other.mId_;
          onChanged();
        }
        if (other.netType_ != 0) {
          setNetTypeValue(other.getNetTypeValue());
        }
        if (other.hasCabin()) {
          mergeCabin(other.getCabin());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object mId_ = "";
      /**
       * <pre>
       *机器码
       * </pre>
       *
       * <code>string m_id = 1;</code>
       */
      public java.lang.String getMId() {
        java.lang.Object ref = mId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *机器码
       * </pre>
       *
       * <code>string m_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMIdBytes() {
        java.lang.Object ref = mId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *机器码
       * </pre>
       *
       * <code>string m_id = 1;</code>
       */
      public Builder setMId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *机器码
       * </pre>
       *
       * <code>string m_id = 1;</code>
       */
      public Builder clearMId() {
        
        mId_ = getDefaultInstance().getMId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *机器码
       * </pre>
       *
       * <code>string m_id = 1;</code>
       */
      public Builder setMIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mId_ = value;
        onChanged();
        return this;
      }

      private int netType_ = 0;
      /**
       * <pre>
       *网络模式
       * </pre>
       *
       * <code>.NetType netType = 2;</code>
       */
      public int getNetTypeValue() {
        return netType_;
      }
      /**
       * <pre>
       *网络模式
       * </pre>
       *
       * <code>.NetType netType = 2;</code>
       */
      public Builder setNetTypeValue(int value) {
        netType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *网络模式
       * </pre>
       *
       * <code>.NetType netType = 2;</code>
       */
      public com.fly.netty.codec.protobuf.MsgReqProtobuf.NetType getNetType() {
        com.fly.netty.codec.protobuf.MsgReqProtobuf.NetType result = com.fly.netty.codec.protobuf.MsgReqProtobuf.NetType.valueOf(netType_);
        return result == null ? com.fly.netty.codec.protobuf.MsgReqProtobuf.NetType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *网络模式
       * </pre>
       *
       * <code>.NetType netType = 2;</code>
       */
      public Builder setNetType(com.fly.netty.codec.protobuf.MsgReqProtobuf.NetType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        netType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *网络模式
       * </pre>
       *
       * <code>.NetType netType = 2;</code>
       */
      public Builder clearNetType() {
        
        netType_ = 0;
        onChanged();
        return this;
      }

      private com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin cabin_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin, com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin.Builder, com.fly.netty.codec.protobuf.MsgReqProtobuf.CabinOrBuilder> cabinBuilder_;
      /**
       * <pre>
       *充电舱
       * </pre>
       *
       * <code>.Cabin cabin = 3;</code>
       */
      public boolean hasCabin() {
        return cabinBuilder_ != null || cabin_ != null;
      }
      /**
       * <pre>
       *充电舱
       * </pre>
       *
       * <code>.Cabin cabin = 3;</code>
       */
      public com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin getCabin() {
        if (cabinBuilder_ == null) {
          return cabin_ == null ? com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin.getDefaultInstance() : cabin_;
        } else {
          return cabinBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *充电舱
       * </pre>
       *
       * <code>.Cabin cabin = 3;</code>
       */
      public Builder setCabin(com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin value) {
        if (cabinBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cabin_ = value;
          onChanged();
        } else {
          cabinBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *充电舱
       * </pre>
       *
       * <code>.Cabin cabin = 3;</code>
       */
      public Builder setCabin(
          com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin.Builder builderForValue) {
        if (cabinBuilder_ == null) {
          cabin_ = builderForValue.build();
          onChanged();
        } else {
          cabinBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *充电舱
       * </pre>
       *
       * <code>.Cabin cabin = 3;</code>
       */
      public Builder mergeCabin(com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin value) {
        if (cabinBuilder_ == null) {
          if (cabin_ != null) {
            cabin_ =
              com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin.newBuilder(cabin_).mergeFrom(value).buildPartial();
          } else {
            cabin_ = value;
          }
          onChanged();
        } else {
          cabinBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *充电舱
       * </pre>
       *
       * <code>.Cabin cabin = 3;</code>
       */
      public Builder clearCabin() {
        if (cabinBuilder_ == null) {
          cabin_ = null;
          onChanged();
        } else {
          cabin_ = null;
          cabinBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *充电舱
       * </pre>
       *
       * <code>.Cabin cabin = 3;</code>
       */
      public com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin.Builder getCabinBuilder() {
        
        onChanged();
        return getCabinFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *充电舱
       * </pre>
       *
       * <code>.Cabin cabin = 3;</code>
       */
      public com.fly.netty.codec.protobuf.MsgReqProtobuf.CabinOrBuilder getCabinOrBuilder() {
        if (cabinBuilder_ != null) {
          return cabinBuilder_.getMessageOrBuilder();
        } else {
          return cabin_ == null ?
              com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin.getDefaultInstance() : cabin_;
        }
      }
      /**
       * <pre>
       *充电舱
       * </pre>
       *
       * <code>.Cabin cabin = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin, com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin.Builder, com.fly.netty.codec.protobuf.MsgReqProtobuf.CabinOrBuilder> 
          getCabinFieldBuilder() {
        if (cabinBuilder_ == null) {
          cabinBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin, com.fly.netty.codec.protobuf.MsgReqProtobuf.Cabin.Builder, com.fly.netty.codec.protobuf.MsgReqProtobuf.CabinOrBuilder>(
                  getCabin(),
                  getParentForChildren(),
                  isClean());
          cabin_ = null;
        }
        return cabinBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Machine)
    }

    // @@protoc_insertion_point(class_scope:Machine)
    private static final com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine();
    }

    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Machine>
        PARSER = new com.google.protobuf.AbstractParser<Machine>() {
      public Machine parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Machine(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Machine> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Machine> getParserForType() {
      return PARSER;
    }

    public com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MsgReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MsgReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>string msgType = 1;</code>
     */
    java.lang.String getMsgType();
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>string msgType = 1;</code>
     */
    com.google.protobuf.ByteString
        getMsgTypeBytes();

    /**
     * <pre>
     *会话ID
     * </pre>
     *
     * <code>string sessionID = 2;</code>
     */
    java.lang.String getSessionID();
    /**
     * <pre>
     *会话ID
     * </pre>
     *
     * <code>string sessionID = 2;</code>
     */
    com.google.protobuf.ByteString
        getSessionIDBytes();

    /**
     * <code>.Machine machine = 3;</code>
     */
    boolean hasMachine();
    /**
     * <code>.Machine machine = 3;</code>
     */
    com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine getMachine();
    /**
     * <code>.Machine machine = 3;</code>
     */
    com.fly.netty.codec.protobuf.MsgReqProtobuf.MachineOrBuilder getMachineOrBuilder();
  }
  /**
   * Protobuf type {@code MsgReq}
   */
  public  static final class MsgReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MsgReq)
      MsgReqOrBuilder {
    // Use MsgReq.newBuilder() to construct.
    private MsgReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgReq() {
      msgType_ = "";
      sessionID_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MsgReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              msgType_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              sessionID_ = s;
              break;
            }
            case 26: {
              com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine.Builder subBuilder = null;
              if (machine_ != null) {
                subBuilder = machine_.toBuilder();
              }
              machine_ = input.readMessage(com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(machine_);
                machine_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fly.netty.codec.protobuf.MsgReqProtobuf.internal_static_MsgReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fly.netty.codec.protobuf.MsgReqProtobuf.internal_static_MsgReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq.class, com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq.Builder.class);
    }

    public static final int MSGTYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object msgType_;
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>string msgType = 1;</code>
     */
    public java.lang.String getMsgType() {
      java.lang.Object ref = msgType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>string msgType = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMsgTypeBytes() {
      java.lang.Object ref = msgType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SESSIONID_FIELD_NUMBER = 2;
    private volatile java.lang.Object sessionID_;
    /**
     * <pre>
     *会话ID
     * </pre>
     *
     * <code>string sessionID = 2;</code>
     */
    public java.lang.String getSessionID() {
      java.lang.Object ref = sessionID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionID_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *会话ID
     * </pre>
     *
     * <code>string sessionID = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIDBytes() {
      java.lang.Object ref = sessionID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MACHINE_FIELD_NUMBER = 3;
    private com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine machine_;
    /**
     * <code>.Machine machine = 3;</code>
     */
    public boolean hasMachine() {
      return machine_ != null;
    }
    /**
     * <code>.Machine machine = 3;</code>
     */
    public com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine getMachine() {
      return machine_ == null ? com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine.getDefaultInstance() : machine_;
    }
    /**
     * <code>.Machine machine = 3;</code>
     */
    public com.fly.netty.codec.protobuf.MsgReqProtobuf.MachineOrBuilder getMachineOrBuilder() {
      return getMachine();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMsgTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msgType_);
      }
      if (!getSessionIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sessionID_);
      }
      if (machine_ != null) {
        output.writeMessage(3, getMachine());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMsgTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msgType_);
      }
      if (!getSessionIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sessionID_);
      }
      if (machine_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getMachine());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq)) {
        return super.equals(obj);
      }
      com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq other = (com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq) obj;

      boolean result = true;
      result = result && getMsgType()
          .equals(other.getMsgType());
      result = result && getSessionID()
          .equals(other.getSessionID());
      result = result && (hasMachine() == other.hasMachine());
      if (hasMachine()) {
        result = result && getMachine()
            .equals(other.getMachine());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMsgType().hashCode();
      hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + getSessionID().hashCode();
      if (hasMachine()) {
        hash = (37 * hash) + MACHINE_FIELD_NUMBER;
        hash = (53 * hash) + getMachine().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MsgReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MsgReq)
        com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fly.netty.codec.protobuf.MsgReqProtobuf.internal_static_MsgReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fly.netty.codec.protobuf.MsgReqProtobuf.internal_static_MsgReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq.class, com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq.Builder.class);
      }

      // Construct using com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msgType_ = "";

        sessionID_ = "";

        if (machineBuilder_ == null) {
          machine_ = null;
        } else {
          machine_ = null;
          machineBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fly.netty.codec.protobuf.MsgReqProtobuf.internal_static_MsgReq_descriptor;
      }

      public com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq getDefaultInstanceForType() {
        return com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq.getDefaultInstance();
      }

      public com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq build() {
        com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq buildPartial() {
        com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq result = new com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq(this);
        result.msgType_ = msgType_;
        result.sessionID_ = sessionID_;
        if (machineBuilder_ == null) {
          result.machine_ = machine_;
        } else {
          result.machine_ = machineBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq) {
          return mergeFrom((com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq other) {
        if (other == com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq.getDefaultInstance()) return this;
        if (!other.getMsgType().isEmpty()) {
          msgType_ = other.msgType_;
          onChanged();
        }
        if (!other.getSessionID().isEmpty()) {
          sessionID_ = other.sessionID_;
          onChanged();
        }
        if (other.hasMachine()) {
          mergeMachine(other.getMachine());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object msgType_ = "";
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>string msgType = 1;</code>
       */
      public java.lang.String getMsgType() {
        java.lang.Object ref = msgType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msgType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>string msgType = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMsgTypeBytes() {
        java.lang.Object ref = msgType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>string msgType = 1;</code>
       */
      public Builder setMsgType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>string msgType = 1;</code>
       */
      public Builder clearMsgType() {
        
        msgType_ = getDefaultInstance().getMsgType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>string msgType = 1;</code>
       */
      public Builder setMsgTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sessionID_ = "";
      /**
       * <pre>
       *会话ID
       * </pre>
       *
       * <code>string sessionID = 2;</code>
       */
      public java.lang.String getSessionID() {
        java.lang.Object ref = sessionID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sessionID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *会话ID
       * </pre>
       *
       * <code>string sessionID = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSessionIDBytes() {
        java.lang.Object ref = sessionID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *会话ID
       * </pre>
       *
       * <code>string sessionID = 2;</code>
       */
      public Builder setSessionID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sessionID_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *会话ID
       * </pre>
       *
       * <code>string sessionID = 2;</code>
       */
      public Builder clearSessionID() {
        
        sessionID_ = getDefaultInstance().getSessionID();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *会话ID
       * </pre>
       *
       * <code>string sessionID = 2;</code>
       */
      public Builder setSessionIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sessionID_ = value;
        onChanged();
        return this;
      }

      private com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine machine_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine, com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine.Builder, com.fly.netty.codec.protobuf.MsgReqProtobuf.MachineOrBuilder> machineBuilder_;
      /**
       * <code>.Machine machine = 3;</code>
       */
      public boolean hasMachine() {
        return machineBuilder_ != null || machine_ != null;
      }
      /**
       * <code>.Machine machine = 3;</code>
       */
      public com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine getMachine() {
        if (machineBuilder_ == null) {
          return machine_ == null ? com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine.getDefaultInstance() : machine_;
        } else {
          return machineBuilder_.getMessage();
        }
      }
      /**
       * <code>.Machine machine = 3;</code>
       */
      public Builder setMachine(com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine value) {
        if (machineBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          machine_ = value;
          onChanged();
        } else {
          machineBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Machine machine = 3;</code>
       */
      public Builder setMachine(
          com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine.Builder builderForValue) {
        if (machineBuilder_ == null) {
          machine_ = builderForValue.build();
          onChanged();
        } else {
          machineBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Machine machine = 3;</code>
       */
      public Builder mergeMachine(com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine value) {
        if (machineBuilder_ == null) {
          if (machine_ != null) {
            machine_ =
              com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine.newBuilder(machine_).mergeFrom(value).buildPartial();
          } else {
            machine_ = value;
          }
          onChanged();
        } else {
          machineBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Machine machine = 3;</code>
       */
      public Builder clearMachine() {
        if (machineBuilder_ == null) {
          machine_ = null;
          onChanged();
        } else {
          machine_ = null;
          machineBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Machine machine = 3;</code>
       */
      public com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine.Builder getMachineBuilder() {
        
        onChanged();
        return getMachineFieldBuilder().getBuilder();
      }
      /**
       * <code>.Machine machine = 3;</code>
       */
      public com.fly.netty.codec.protobuf.MsgReqProtobuf.MachineOrBuilder getMachineOrBuilder() {
        if (machineBuilder_ != null) {
          return machineBuilder_.getMessageOrBuilder();
        } else {
          return machine_ == null ?
              com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine.getDefaultInstance() : machine_;
        }
      }
      /**
       * <code>.Machine machine = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine, com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine.Builder, com.fly.netty.codec.protobuf.MsgReqProtobuf.MachineOrBuilder> 
          getMachineFieldBuilder() {
        if (machineBuilder_ == null) {
          machineBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine, com.fly.netty.codec.protobuf.MsgReqProtobuf.Machine.Builder, com.fly.netty.codec.protobuf.MsgReqProtobuf.MachineOrBuilder>(
                  getMachine(),
                  getParentForChildren(),
                  isClean());
          machine_ = null;
        }
        return machineBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:MsgReq)
    }

    // @@protoc_insertion_point(class_scope:MsgReq)
    private static final com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq();
    }

    public static com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgReq>
        PARSER = new com.google.protobuf.AbstractParser<MsgReq>() {
      public MsgReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MsgReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgReq> getParserForType() {
      return PARSER;
    }

    public com.fly.netty.codec.protobuf.MsgReqProtobuf.MsgReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Cabin_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Cabin_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Machine_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Machine_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MsgReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MsgReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014msgreq.proto\"X\n\005Cabin\022\014\n\004c_id\030\001 \001(\t\022\014\n" +
      "\004p_id\030\002 \001(\t\022\016\n\006p_lock\030\003 \001(\010\022\017\n\007p_count\030\004" +
      " \001(\005\022\022\n\np_quantity\030\005 \001(\005\"I\n\007Machine\022\014\n\004m" +
      "_id\030\001 \001(\t\022\031\n\007netType\030\002 \001(\0162\010.NetType\022\025\n\005" +
      "cabin\030\003 \001(\0132\006.Cabin\"G\n\006MsgReq\022\017\n\007msgType" +
      "\030\001 \001(\t\022\021\n\tsessionID\030\002 \001(\t\022\031\n\007machine\030\003 \001" +
      "(\0132\010.Machine*\037\n\007NetType\022\010\n\004wifi\020\000\022\n\n\006mob" +
      "ile\020\001B.\n\034com.fly.netty.codec.protobufB\016M" +
      "sgReqProtobufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Cabin_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Cabin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Cabin_descriptor,
        new java.lang.String[] { "CId", "PId", "PLock", "PCount", "PQuantity", });
    internal_static_Machine_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Machine_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Machine_descriptor,
        new java.lang.String[] { "MId", "NetType", "Cabin", });
    internal_static_MsgReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_MsgReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MsgReq_descriptor,
        new java.lang.String[] { "MsgType", "SessionID", "Machine", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
